
a1 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh','4G','Pri. LTE','NB-IoT','UHF','LoRa'))
a2 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
combine <- merge(a1,a2)



a3 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a4 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a5 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a6 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a7 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a8 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a9 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))

a10 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a11 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a12 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a13 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a14 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a15 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a16 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a17 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a18 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a19 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))

a20 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a21 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a22 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a23 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a24 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a25 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a26 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a27 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a28 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a29 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))

a30 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a31 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a32 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a33 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a34 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a35 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a36 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a37 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a38 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a39 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))

a40 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a41 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a42 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a43 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a44 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a45 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a46 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a47 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a48 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a49 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))

a50 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a51 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a52 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a53 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a54 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a55 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a56 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a57 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a58 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a59 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))

a60 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a61 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))
a62 <- data.frame(Tech = c('NBPLC','Fiber','ZigBee','WiFi','RF-Mesh' ,	'4G','Pri. LTE','NB-IoT','UHF','LoRa','5G','SATCOM'))




assign("a1", a1)
assign("a2", a2)
assign("a3", a3)
assign("a4", a4)
assign("a5", a5)
assign("a6", a6)
assign("a7", a7)
assign("a8", a8)
assign("a9", a9)

assign("a10", a10)
assign("a11", a11)
assign("a12", a12)
assign("a13", a13)
assign("a14", a14)
assign("a15", a15)
assign("a16", a16)
assign("a17", a17)
assign("a18", a18)

assign("a19", a19)
assign("a20", a20)
assign("a21", a21)
assign("a22", a22)
assign("a23", a23)
assign("a24", a24)
assign("a25", a25)
assign("a26", a26)
assign("a27", a27)
assign("a28", a28)
assign("a29", a29)
assign("a30", a30)
assign("a31", a31)
assign("a32", a32)
assign("a33", a33)
assign("a34", a34)
assign("a35", a35)

assign("a36", a36)
assign("a37", a37)
assign("a38", a38)


assign("a1", a1)
assign("a2", a2)
assign("a3", a3)
assign("a4", a4)
assign("a5", a5)
assign("a6", a6)
assign("a7", a7)
assign("a8", a8)
assign("a9", a9)


